// <auto-generated />
using System;
using CVD.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CVD.Migrations
{
    [DbContext(typeof(CvdDbContext))]
    [Migration("20220910120158_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CVD.Domain.Entitites.Department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("department");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "D1"
                        },
                        new
                        {
                            id = 2,
                            name = "D2"
                        },
                        new
                        {
                            id = 3,
                            name = "D3"
                        });
                });

            modelBuilder.Entity("CVD.Domain.Entitites.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("chief_id")
                        .HasColumnType("integer");

                    b.Property<int>("department_id")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("salary")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("department_id");

                    b.ToTable("employee");

                    b.HasData(
                        new
                        {
                            id = 1,
                            chief_id = 5,
                            department_id = 1,
                            name = "John",
                            salary = 100
                        },
                        new
                        {
                            id = 2,
                            chief_id = 5,
                            department_id = 1,
                            name = "Misha",
                            salary = 600
                        },
                        new
                        {
                            id = 3,
                            chief_id = 6,
                            department_id = 2,
                            name = "Eugen",
                            salary = 300
                        },
                        new
                        {
                            id = 4,
                            chief_id = 6,
                            department_id = 2,
                            name = "Tolya",
                            salary = 400
                        },
                        new
                        {
                            id = 5,
                            chief_id = 7,
                            department_id = 3,
                            name = "Stepan",
                            salary = 500
                        },
                        new
                        {
                            id = 6,
                            chief_id = 7,
                            department_id = 3,
                            name = "Alex",
                            salary = 1000
                        },
                        new
                        {
                            id = 7,
                            department_id = 3,
                            name = "Ivan",
                            salary = 1100
                        });
                });

            modelBuilder.Entity("CVD.Domain.Entitites.Employee", b =>
                {
                    b.HasOne("CVD.Domain.Entitites.Department", "department")
                        .WithMany()
                        .HasForeignKey("department_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });
#pragma warning restore 612, 618
        }
    }
}
